environment:
  matrix:
    - MINICONDA: C:\Miniconda-x64
    - MINICONDA: C:\Miniconda35-x64
    - MINICONDA: C:\Miniconda36-x64
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda install --yes "pip" "setuptools>=27.3"
  - conda install --yes "six>=1.5" "python-dateutil" "numpy>=1.7.1" "scipy>=0.12.1" "matplotlib>=1.2.0" "astropy>=1.1.1" "h5py>=1.3" "ligo-segments>=1.0.0" "tqdm>=4.10.0" "ligotimegps"
  - conda install --yes "pytest>=3.1" "pytest-runner" "coverage>=4.0.0" "freezegun>=0.2.3" "sqlparse>=0.2.0" "beautifulsoup4"
build_script:
  - python -m pip install .
test_script:
  - python setup.py test
