name: gwpy
channels:
  - conda-forge
dependencies:
  - pip
  - python
  # include things that aren't (easily) installed using pip
  - ligo-segments
  - python-framel
  - python-ldas-tools-framecpp
  - python-nds2-client
