name: gwpy
channels:
  - conda-forge
dependencies:
  - graphviz
  - igwn-ligolw
  - pycbc
  - python
  - python-framel
  - python-gssapi
  - python-lalframe
  - python-ldas-tools-framecpp
  - python-nds2-client
